# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PastelCodingTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PastelCodingTest
 
  pod "Alamofire"
  pod "RealmSwift"
  
  
  pod 'SDWebImage', '~> 5.0'

  target 'PastelCodingTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PastelCodingTestUITests' do
    # Pods for testing
  end

end
